# frozen_string_literal: true

require_relative '../card_container'

module Doomlings
  # S Cards
  CardContainer.add_basic_card('SALIVA', :blue, 'Classic', 1)
  CardContainer.add_basic_card('SAUDADE', :colourless, 'Classic', 2)
  CardContainer.add_basic_card('SCUTES', :blue, 'Classic', 3)
  # CardContainer.add_basic_card('SEA KINGDOMS', :blue, 'Classic', ??)
  CardContainer.add_basic_card('SELECTIVE MEMORY', :blue, 'Classic', 0)
  CardContainer.add_basic_card('SELF-AWARENESS', :colourless, 'Classic', -1)
  CardContainer.add_basic_card('SELF-REPLICATING', :green, 'Classic', 0)
  CardContainer.add_basic_card('SELFISH', :purple, 'Classic', 1)
  CardContainer.add_basic_card('SENTIENCE', :red, 'Classic', 2)
  CardContainer.add_basic_card('SERRATED TEETH', :red, 'Dinolings', 5)
  CardContainer.add_basic_card('SNEAKY', :purple, 'Classic', 2)
  # CardContainer.add_basic_card('SOLAR FLARE', :red, 'Classic', ??)
  CardContainer.add_basic_card('SPINY', :blue, 'Classic', 1)
  CardContainer.add_basic_card('STICKY SECRETIONS', :purple, 'Classic', -1)
  CardContainer.add_basic_card('STONE SKIN', :red, 'Classic', 2)
  CardContainer.add_basic_card('SUBDERMAL PLATING', :purple, 'Techlings', -1)
  CardContainer.add_basic_card('SUPER SPREADER', :purple, 'Classic', 2)
  # CardContainer.add_basic_card('SUPER VOLCANO', :red, 'Classic', ??)
  CardContainer.add_basic_card('SWARM (1)', :green, 'Classic', 0)
  CardContainer.add_basic_card('SWARM (2)', :green, 'Classic', 0)
  CardContainer.add_basic_card('SWARM (3)', :green, 'Classic', 0)
  CardContainer.add_basic_card('SWARM (4)', :green, 'Classic', 0)
  CardContainer.add_basic_card('SWARM (5)', :green, 'Classic', 0)
  CardContainer.add_basic_card('SWARM (6)', :green, 'Classic', 0)
  CardContainer.add_basic_card('SWEAT', :blue, 'Classic', 2)
  CardContainer.add_basic_card('SYMBIOSIS', :green, 'Classic', 3)

  # T Cards
  CardContainer.add_basic_card('TALONS', :purple, 'Dinolings', 2)
  # CardContainer.add_basic_card('TECTONIC SHIFT', :green, 'Classic', ??)
  CardContainer.add_basic_card('TEETH', :purple, 'Classic', 1)
  CardContainer.add_basic_card('TELEKINETIC', :purple, 'Classic', 1)
  # CardContainer.add_basic_card('TEMPORAL SANDS', :red, 'Classic', ??)
  CardContainer.add_basic_card('TENTACLES', :blue, 'Classic', 1)
  CardContainer.add_basic_card('TERRITORIAL', :red, 'Classic', 1)
  CardContainer.add_basic_card('TERROR BEAK', :blue, 'Dinolings', 3)
  CardContainer.add_basic_card('TETRACHROMATIC', :purple, 'multi-colour', 4)
  CardContainer.add_basic_card('THAGOMIZER', :green, 'Dinolings', 1)
  # CardContainer.add_basic_card('THE BIG ONE', :green, 'Classic', ??)
  # CardContainer.add_basic_card('THE BILBIES', :colourless, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE BIRTH OF LIFE', :colourless, 'Classic', ??)
  # CardContainer.add_basic_card('THE CABOCHON', :red, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE COSMIC JINX', :purple, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE DANCER', :colourless, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE FELLMONGER', :red, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE FOUR HORSEMEN', :colourless, 'Classic', ??)
  # CardContainer.add_basic_card('THE JELLYFISH', :purple, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE LOGICIAN', :colourless, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE LUMBERJACK', :green, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE MAGICIAN', :colourless, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE MAVEN', :blue, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE MESSIAH', :red, 'Classic', ??)
  # CardContainer.add_basic_card('THE SOOTHSAYER', :blue, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE SPIRIT GARDENER', :green, 'Meaning of Life', ??)
  CardContainer.add_basic_card('THE THIRD EYE', :colourless, 'Classic', 0)
  # CardContainer.add_basic_card('THE TIGRIS', :red, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE VAGRANT', :red, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE VIXEN', :blue, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE WARBLER', :green, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE WARRIOR', :red, 'Meaning of Life', ??)
  # CardContainer.add_basic_card('THE WEAVER', :purple, 'Meaning of Life', ??)
  CardContainer.add_basic_card('TINY', :blue, 'Classic', 17)
  CardContainer.add_basic_card('TINY ARMS', :red, 'Dinolings', -1)
  CardContainer.add_basic_card('TINY LITTLE MELONS', :green, 'Classic', 1)
  CardContainer.add_basic_card('TRANSGENIC MODIFICATION', :green, 'Techlings', 1)
  # CardContainer.add_basic_card('TROPICAL LANDS', :green, 'Classic', ??)
  CardContainer.add_basic_card('TRUNK', :green, 'Classic', 1)
  CardContainer.add_basic_card('TUBE FEET', :blue, 'KSE', 2)

  # V Cards
  CardContainer.add_basic_card('VAMPIRISM', :purple, 'Classic', 3)
  CardContainer.add_basic_card('VENOMOUS', :purple, 'Classic', -2)
  CardContainer.add_basic_card('VIRAL', :purple, 'Classic', 2)
  CardContainer.add_basic_card('VORACIOUS', :red, 'Classic', 2)

  # W Cards
  CardContainer.add_basic_card('WARM BLOOD', :red, 'Classic', -1)
  CardContainer.add_basic_card('WITCHY', :purple, 'Mythlings', 2)
  CardContainer.add_basic_card('WOODY STEMS', :green, 'Classic', 1)

  # Z Cards
  CardContainer.add_basic_card('ZOMBIFIED', :purple, 'Mythlings', -2)
end
